import React, { ReactChild } from "react";
import { SemanticICONS } from "semantic-ui-react";

interface MyIconProps
{
    name: string;
    size?: IconSize;
    color?: IconColor;
    rotate?: IconRotation;
    disabled?: boolean;
    loading?: boolean;
    fitted?: boolean;
    link?: boolean;
    flipped?: boolean;
    circular?: boolean;
    bordered?: boolean;
    inverted?: boolean;
    className?: string;
    children?: ReactChild;
}

const MyIcon = (props: MyIconProps & React.HTMLAttributes<HTMLElement>) =>
{
    let myClassName = "icon";

    const { name, size, color, rotate, disabled, loading, fitted, link, flipped, circular, bordered,
        inverted, className, children, ...others } = props;

    if (props.name.startsWith("vs-") && props.inverted)
    {
        myClassName += " vs-dark-" + props.name.substring(3);
    }
    else if (props.name.startsWith("vs-"))
    {
        myClassName += " vs-light-" + props.name.substring(3);
    }
    else
    {
        myClassName += " " + props.name;
    }

    props.size && (myClassName += " " + props.size);
    props.color && (myClassName += " " + props.color);
    props.rotate && (myClassName += " " + props.rotate);
    props.disabled && (myClassName += " disabled");
    props.loading && (myClassName += " loading");
    props.fitted && (myClassName += " fitted");
    props.link && (myClassName += " link");
    props.flipped && (myClassName += " flipped");
    props.circular && (myClassName += " circular");
    props.bordered && (myClassName += " bordered");
    props.inverted && (myClassName += " inverted");
    props.className && (myClassName += " " + props.className);

    return <i className={myClassName} {...others}>{props.children}</i>;
};

export default MyIcon;

export type IconSize = "mini"
    | "tiny"
    | "small"
    | "large"
    | "big"
    | "huge"
    | "massive";

export type IconRotation = "rotated clockwise" | "rotated counterclockwise";

export type IconColor = ""
    | "red"
    | "orange"
    | "yellow"
    | "olive"
    | "green"
    | "teal"
    | "blue"
    | "violet"
    | "purple"
    | "pink"
    | "brown"
    | "grey"
    | "black";

export type IconName = SemanticICONS | VisualStudioCodeIconName;

type VisualStudioCodeIconName = "vs-account"
    | "vs-activate-breakpoints"
    | "vs-add"
    | "vs-archive"
    | "vs-arrow-both"
    | "vs-arrow-down"
    | "vs-arrow-left"
    | "vs-arrow-right"
    | "vs-arrow-small-down"
    | "vs-arrow-small-left"
    | "vs-arrow-small-right"
    | "vs-arrow-small-up"
    | "vs-arrow-up"
    | "vs-beaker"
    | "vs-bell-dot"
    | "vs-bell"
    | "vs-blocked"
    | "vs-bold"
    | "vs-bookmark"
    | "vs-book"
    | "vs-briefcase"
    | "vs-broadcast"
    | "vs-browser"
    | "vs-bug"
    | "vs-build"
    | "vs-calendar"
    | "vs-call-incoming"
    | "vs-call-outgoing"
    | "vs-case-sensitive"
    | "vs-checklist"
    | "vs-check"
    | "vs-chevron-down"
    | "vs-chevron-left"
    | "vs-chevron-right"
    | "vs-chevron-up"
    | "vs-chrome-close"
    | "vs-chrome-maximize"
    | "vs-chrome-minimize"
    | "vs-chrome-restore"
    | "vs-circle-filled"
    | "vs-circle-outline"
    | "vs-circle-slash"
    | "vs-circuit-board"
    | "vs-clear-all"
    | "vs-clippy"
    | "vs-close-all"
    | "vs-close"
    | "vs-cloud-download"
    | "vs-cloud"
    | "vs-cloud-upload"
    | "vs-code"
    | "vs-collapse-all"
    | "vs-color-mode"
    | "vs-comment-discussion-quote"
    | "vs-comment-discussion"
    | "vs-comment"
    | "vs-console"
    | "vs-credit-card"
    | "vs-dashboard"
    | "vs-dash"
    | "vs-database"
    | "vs-debug-alt-small"
    | "vs-debug-alt"
    | "vs-debug-breakpoint-conditional"
    | "vs-debug-breakpoint-conditional-unverified"
    | "vs-debug-breakpoint-data"
    | "vs-debug-breakpoint-data-unverified"
    | "vs-debug-breakpoint-function"
    | "vs-debug-breakpoint-function-unverified"
    | "vs-debug-breakpoint-log"
    | "vs-debug-breakpoint-log-unverified"
    | "vs-debug-breakpoint-stackframe-active"
    | "vs-debug-breakpoint-stackframe-dot"
    | "vs-debug-breakpoint-stackframe"
    | "vs-debug-breakpoint-unsupported"
    | "vs-debug-console"
    | "vs-debug-continue"
    | "vs-debug-disconnect"
    | "vs-debug-pause"
    | "vs-debug-restart-frame"
    | "vs-debug-restart"
    | "vs-debug-reverse-continue"
    | "vs-debug-start"
    | "vs-debug-step-back"
    | "vs-debug-step-into"
    | "vs-debug-step-out"
    | "vs-debug-step-over"
    | "vs-debug-stop"
    | "vs-debug"
    | "vs-desktop-download"
    | "vs-device-camera"
    | "vs-device-camera-video"
    | "vs-device-mobile"
    | "vs-diff-added"
    | "vs-diff-ignored"
    | "vs-diff-modified"
    | "vs-diff-removed"
    | "vs-diff-renamed"
    | "vs-diff"
    | "vs-discard"
    | "vs-editor-layout"
    | "vs-edit"
    | "vs-ellipsis"
    | "vs-empty-window"
    | "vs-error"
    | "vs-exclude"
    | "vs-expand-all"
    | "vs-export"
    | "vs-extensions"
    | "vs-eye-closed"
    | "vs-eye"
    | "vs-feedback"
    | "vs-file-binary"
    | "vs-file-code"
    | "vs-file-media"
    | "vs-file-pdf"
    | "vs-files"
    | "vs-file-submodule"
    | "vs-file"
    | "vs-file-symlink-directory"
    | "vs-file-symlink-file"
    | "vs-file-zip"
    | "vs-filter"
    | "vs-flame"
    | "vs-fold-down"
    | "vs-folder-active"
    | "vs-folder-opened"
    | "vs-folder"
    | "vs-fold"
    | "vs-fold-up"
    | "vs-gear"
    | "vs-gift"
    | "vs-gist-secret"
    | "vs-gist"
    | "vs-git-commit"
    | "vs-git-compare"
    | "vs-github-action"
    | "vs-github-inverted"
    | "vs-git-merge"
    | "vs-git-pull-request"
    | "vs-globe"
    | "vs-go-to-file"
    | "vs-grabber"
    | "vs-graph-left"
    | "vs-graph"
    | "vs-gripper"
    | "vs-group-by-ref-type"
    | "vs-heart"
    | "vs-help"
    | "vs-history"
    | "vs-home"
    | "vs-horizontal-rule"
    | "vs-hubot"
    | "vs-inbox"
    | "vs-info"
    | "vs-issue-closed"
    | "vs-issue-reopened"
    | "vs-issues"
    | "vs-italic"
    | "vs-jersey"
    | "vs-json"
    | "vs-kebab-vertical"
    | "vs-key"
    | "vs-law"
    | "vs-library"
    | "vs-lightbulb-autofix"
    | "vs-lightbulb"
    | "vs-link-external"
    | "vs-link"
    | "vs-list-filter"
    | "vs-list-flat"
    | "vs-list-ordered"
    | "vs-list-selection"
    | "vs-list-tree"
    | "vs-list-unordered"
    | "vs-loading"
    | "vs-location"
    | "vs-lock"
    | "vs-magnet"
    | "vs-mail-read"
    | "vs-mail"
    | "vs-markdown"
    | "vs-megaphone"
    | "vs-mention"
    | "vs-menu"
    | "vs-merge"
    | "vs-milestone"
    | "vs-mirror"
    | "vs-more"
    | "vs-mortar-board"
    | "vs-move"
    | "vs-multiple-windows"
    | "vs-mute"
    | "vs-new-file"
    | "vs-new-folder"
    | "vs-no-newline"
    | "vs-note"
    | "vs-octoface"
    | "vs-open-preview"
    | "vs-organization"
    | "vs-output"
    | "vs-package"
    | "vs-paintcan"
    | "vs-pass"
    | "vs-person"
    | "vs-pinned"
    | "vs-pin"
    | "vs-play-circle"
    | "vs-plug"
    | "vs-preserve-case"
    | "vs-preview"
    | "vs-primitive-square"
    | "vs-project"
    | "vs-pulse"
    | "vs-question"
    | "vs-quotes"
    | "vs-quote"
    | "vs-radio-tower"
    | "vs-reactions"
    | "vs-record-keys"
    | "vs-record-start"
    | "vs-record-stop"
    | "vs-record"
    | "vs-references"
    | "vs-refresh"
    | "vs-regex"
    | "vs-remote-explorer"
    | "vs-remote"
    | "vs-remove"
    | "vs-rename"
    | "vs-replace-all"
    | "vs-replace"
    | "vs-reply"
    | "vs-repo-clone"
    | "vs-repo-force-push"
    | "vs-repo-forked"
    | "vs-repo-pull"
    | "vs-repo-push"
    | "vs-report"
    | "vs-repo"
    | "vs-request-changes"
    | "vs-rocket"
    | "vs-root-folder-opened"
    | "vs-root-folder"
    | "vs-rss"
    | "vs-ruby"
    | "vs-run-above"
    | "vs-run-all"
    | "vs-run-below"
    | "vs-run"
    | "vs-save-all"
    | "vs-save-as"
    | "vs-save"
    | "vs-screen-full"
    | "vs-screen-normal"
    | "vs-search-stop"
    | "vs-search"
    | "vs-server-environment"
    | "vs-server-process"
    | "vs-server"
    | "vs-settings-gear"
    | "vs-settings"
    | "vs-shield"
    | "vs-sign-in"
    | "vs-sign-out"
    | "vs-smiley"
    | "vs-sort-precedence"
    | "vs-source-control"
    | "vs-split-horizontal"
    | "vs-split-vertical"
    | "vs-squirrel"
    | "vs-star-empty"
    | "vs-star-full"
    | "vs-star-half"
    | "vs-stop-circle"
    | "vs-symbol-array"
    | "vs-symbol-boolean"
    | "vs-symbol-class"
    | "vs-symbol-color"
    | "vs-symbol-constant"
    | "vs-symbol-enum-member"
    | "vs-symbol-enum"
    | "vs-symbol-event"
    | "vs-symbol-field"
    | "vs-symbol-file"
    | "vs-symbol-interface"
    | "vs-symbol-key"
    | "vs-symbol-keyword"
    | "vs-symbol-method"
    | "vs-symbol-misc"
    | "vs-symbol-namespace"
    | "vs-symbol-numeric"
    | "vs-symbol-operator"
    | "vs-symbol-parameter"
    | "vs-symbol-property"
    | "vs-symbol-ruler"
    | "vs-symbol-snippet"
    | "vs-symbol-string"
    | "vs-symbol-structure"
    | "vs-symbol-variable"
    | "vs-sync-ignored"
    | "vs-sync"
    | "vs-tag"
    | "vs-tasklist"
    | "vs-telescope"
    | "vs-terminal"
    | "vs-text-size"
    | "vs-three-bars"
    | "vs-thumbsdown"
    | "vs-thumbsup"
    | "vs-tools"
    | "vs-trash"
    | "vs-triangle-down"
    | "vs-triangle-left"
    | "vs-triangle-right"
    | "vs-triangle-up"
    | "vs-twitter"
    | "vs-unfold"
    | "vs-ungroup-by-ref-type"
    | "vs-unlock"
    | "vs-unmute"
    | "vs-unverified"
    | "vs-verified"
    | "vs-versions"
    | "vs-vm-active"
    | "vs-vm-connect"
    | "vs-vm-outline"
    | "vs-vm-pending"
    | "vs-vm-running"
    | "vs-vm"
    | "vs-warning"
    | "vs-watch"
    | "vs-whitespace"
    | "vs-whole-word"
    | "vs-window"
    | "vs-word-wrap"
    | "vs-zoom-in"
    | "vs-zoom-out";