import fs from "fs";
import { compile } from "json-schema-to-typescript";
import { dirname } from "path";
import schemas from "./schemas";

const OUTPUT_FILE = "./src/generated/dtos.d.ts";

const options = {
    bannerComment: "",
    declareExternallyReferenced: false,
    style: {
        bracketSpacing: false,
        printWidth: 80,
        semi: true,
        singleQuote: false,
        tabWidth: 4,
        useTabs: false
    }
};

async function generate()
{
    // Delete output file if it exists
    if (fs.existsSync(OUTPUT_FILE))
    {
        fs.rmSync(OUTPUT_FILE);
    }

    // Create containing directory of output file
    fs.mkdirSync(dirname(OUTPUT_FILE), { recursive: true });

    // Create file
    fs.appendFileSync(OUTPUT_FILE, "// This file was generated by src/genTypes.ts. Do not edit.\n\n");

    // Iterate through the schemas and append generated code to the output file
    for (const [name, schema] of Object.entries(schemas))
    {
        const text = await compile(schema, name, options);
        fs.appendFileSync(OUTPUT_FILE, text + "\n");
    }
}

generate();